apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: amq-cluster
spec:
  kafka:
    replicas: 3
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 4Gi
  zookeeper:
    replicas: 3
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi