apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: amq-cluster
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dedicated
            operator: In
            values:
            - Kafka
  kafka:
    replicas: 3
    storage:
      size: 100Gi
    resources:
      limits:
        memory: 8Gi
      requests:
        cpu: '3'
        memory: 8Gi
  zookeeper:
    replicas: 3
    storage:
      size: 100Gi
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: '2'
        memory: 4Gi