apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: amq-cluster
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dedicated
            operator: In
            values:
            - Kafka
  kafka:
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "Kafka"
            effect: "NoSchedule"
    replicas: 2
    storage:
      size: 10Gi
    resources:
      limits:
        memory: 8Gi
      requests:
        cpu: '3'
        memory: 8Gi
  zookeeper:
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "Kafka"
            effect: "NoSchedule"
    replicas: 2
    storage:
      size: 10Gi    
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: '2'
        memory: 4Gi