apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: amq-cluster
spec:
  kafka:
    version: 3.6.0
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - name: tls
      port: 9093
      tls: true
      type: internal
    - name: ext
      port: 9094
      tls: true
      type: route
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    config:
      default.replication.factor: 1
      inter.broker.protocol.version: "3.6"
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    storage:
      type: ephemeral
#      class: thin-csi
#      size: 10Gi
#      type: persistent-claim
#    metricsConfig:
#      type: jmxPrometheusExporter
#      valueFrom:
#        configMapKeyRef:
#          name: kafka-metrics
#          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 1
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    storage:
      type: ephemeral
#      class: thin-csi
#      size: 10Gi
#      type: persistent-claim
#    metricsConfig:
#      type: jmxPrometheusExporter
#      valueFrom:
#        configMapKeyRef:
#          name: kafka-metrics
#          key: zookeeper-metrics-config.yml
  entityOperator:
    topicOperator:
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: '1'
          memory: 1Gi
      readinessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 10
      livenessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 10
    userOperator:
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: '1'
          memory: 1Gi
      readinessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 10
      livenessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 10
#  kafkaExporter:
#    topicRegex: ".*"
#    groupRegex: ".*"